// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0a763014-faa7-451e-b3da-658b1e5d5f45",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_RRIdOHeBW",
    "aws_user_pools_web_client_id": "7rk2hosalghk2cteu734kr53dn",
    "oauth": {},
    "predictions": {
        "identify": {
            "identifyText": {
                "proxy": false,
                "region": "us-east-1",
                "defaults": {
                    "format": "ALL"
                }
            }
        }
    }
};


export default awsmobile;
